### PR TITLE
Attributes with 'v2x' are serialized as 'V2x', but should be serialized as 'V2X'

### PR DESCRIPTION
**Pull request by Jared-Newell-Mobility**

### CODE REVIEW

**Comment by Jared-Newell-Mobility** [comment]
This is the example you gave in https://github.com/mobilityhouse/ocpp/issues/431

**Comment by OrangeTux** [comment]
Can you add a test to cover the change?

**Comment by OrangeTux** [comment]
> This is the example you gave in https://github.com/mobilityhouse/ocpp/issues/431

Lol, I must have forgotten this.

**Review by tmh-grunwald-markus — APPROVED** [review]
The handling of `V2X` is ok, but to avoid confusion I would handle `SoC` at the start of a word in the same way (which is not the point of THIS PR).

**Review by OrangeTux — APPROVED** [review]
LGTM

**Pull request merged**
