### PR TITLE
add ConfigurationKeys

### PR DESCRIPTION
**Pull request by lbbrhzn**
added configuration keys (for v16 only)

### CODE REVIEW

**Comment by lbbrhzn** [comment]
i added the configuration keys to enums.py, not sure if you need to update your schema_to_enums.pu script to prevent them from being overwritten.

**Comment by lbbrhzn** [comment]
Also, might be nice to separate the keys for the different profiles. What would be a good way to do that?

**Comment by tropxy** [comment]
Thanks for this @lbbrhzn, I guess you manually added all the keys, right? in order to avoid losing data, what I think we could do is to add an extra file, containing the original OCPP config keys, for 1.6 and read from there when we run the schema_to_enums.py, but not sure if it is the best idea

**Comment by lbbrhzn** [comment]
Not sure either. Perhaps that's something you can do in a new pull request?

**Comment by OrangeTux** [comment]
This PR is superseded by #413. Thanks @lbbrhzn

**Pull request closed without merging**
