### PR TITLE
fix: DataTransfer data types

### PR DESCRIPTION
**Pull request by mdwcrft**
In 2.0.1 both DataTransferRequest and DataTransferResponse have a field called `data` which is defined as `AnyType` so I believe these should both by of type `Any` here

### CODE REVIEW

**Review by Jared-Newell-Mobility — APPROVED** [review]

**Review by Jared-Newell-Mobility — CHANGES_REQUESTED** [review]
Nice catch, could you also add an entry in the ChangeLog.md?

**Review by Jared-Newell-Mobility — APPROVED** [review]

**Review by OrangeTux — APPROVED** [review]

**Comment by malsyned** [comment]
My read on the spec for this is different. The Field Type for `data` in both `DataTransferRequest` and `DataTransferResponse` is indeed listed as `anyType`. However, in **2.1.3. Primitive Datatypes**, `AnyType` is defined as "**Text**, data without specified length or format" (emphasis mine). So I think the correct Python data type for this should be `str`, not `Any`.

This is a pretty confusing part of the spec, though, I could certainly be wrong. It looks like it has a mistake in it as well, because the capitalization isn't consistent between the Field Types `anyType` and the Primitive Datatype name `AnyType`. Maybe this part of the spec needs some TLC in the next revision.

**Comment by OrangeTux** [comment]
@malsyned Good catch! You're right. I think we should revert this change.

**Comment by mdwcrft** [comment]
> My read on the spec for this is different. The Field Type for `data` in both `DataTransferRequest` and `DataTransferResponse` is indeed listed as `anyType`. However, in **2.1.3. Primitive Datatypes**, `AnyType` is defined as "**Text**, data without specified length or format" (emphasis mine). So I think the correct Python data type for this should be `str`, not `Any`.

Interesting, I read "Text, data" to mean "Text OR data" - agreed it's not clear though I think @OrangeTux will ask the OCA for a clarification

**Pull request merged**
