### PR TITLE
add executor to validate_payload

### PR DESCRIPTION
**Pull request by drc38**
Addresses issue #647

### CODE REVIEW

**Comment by drc38** [comment]
> Hi @drc38, the changes look good. I believe the functionality will not break and it is backwards compatible as well.
> 
> Here's another thought: Instead of using `run_in_executor` to run the blocking `validate_payload` function call, what if we convert the `validate_payload` function into a pure async function with all I/O calls being non-blocking.

That would be result in quite a departure from the current structure where most functions are not async. Another approach is to use https://github.com/Tinche/aiofiles for the file open, assuming you're happy to import aiofiles as part of the project.

**Comment by drc38** [comment]
> That would result in quite a departure from the current structure where most functions are not async. Another approach is to use https://github.com/Tinche/aiofiles for the file open, assuming you're happy to import aiofiles as part of the project.

Actually using aiofiles would still require a rewrite to async. I think the proposed approach is the best for now.

**Comment by jainmohit2001** [comment]
LGTM.

**Review by proelke — APPROVED** [review]

**Comment by drc38** [comment]
@proelke @jainmohit2001 Thank you both for continuing to maintain the library,  are we able to get a PyPi release that includes this merge please.

**Comment by N3rdix** [comment]
Bumping this, can we support somehow to get a PyPi release shipped?

**Comment by mdwcrft** [comment]
@N3rdix @drc38 discussion on a new release is on #675 - aiming for this weekend

**Pull request merged**
