### PR TITLE
bugfix: Changed total_cost type from Optional[int] to Optional[float]

### LINKED ISSUE #657: TransactionEventPayload total_cost should be a floating point number
```
@dataclass
class TransactionEventPayload:
    total_cost: Optional[int] = None
    charging_priority: Optional[int] = None
    id_token_info: Optional[Dict] = None
    updated_personal_message: Optional[Dict] = None
    custom_data: Optional[Dict[str, Any]] = None
```

According to the ocpp 2.0.1 spec, total_cost should be a 'decimal', not an int.

### PR DESCRIPTION
**Pull request by jainmohit2001**
Fixes #657

### CODE REVIEW

**Review by OrangeTux — APPROVED** [review]

**Comment by jainmohit2001** [comment]
There seems to be some issue with the `tests (3.7)` check.

**Comment by OrangeTux** [comment]
Python 3.7 [is not supported](https://github.com/mobilityhouse/ocpp/commit/74e94d43457d7bd97f2f214b1c269d6370711448) anymore. I've no idea what that check is still shown in Github. You can ignore GH .

**Comment by jainmohit2001** [comment]
> Python 3.7 [is not supported](https://github.com/mobilityhouse/ocpp/commit/74e94d43457d7bd97f2f214b1c269d6370711448) anymore. I've no idea what that check is still shown in Github. You can ignore GH .

Can you check settings for the repo? I think under the branch management or branch rules, we should be able to find this check. We need to manually remove it from there.

**Comment by proelke** [comment]
It is now removed from the branch protection rules

**Pull request merged**
