### PR TITLE
fix typo in DataTypeEnum -> value_too_high

### PR DESCRIPTION
**Pull request by d2avids**
I found a typo. Consider accepting it if it's possible

### CODE REVIEW

**Comment by Jared-Newell-Mobility** [comment]
Nice Catch!

**Review by Jared-Newell-Mobility — DISMISSED** [review]

**Comment by Jared-Newell-Mobility** [comment]
If you could also add an entry to the change log, that would be great

**Comment by d2avids** [comment]
@Jared-Newell-Mobility I've added an entry to the changelog and created a relevant issue for that [here](https://github.com/mobilityhouse/ocpp/issues/613)

**Review by Jared-Newell-Mobility — APPROVED** [review]
Looks good and thank-you

**Pull request merged**
