### PR TITLE
feat: add optional param for passing a custom logger to ChargePoint

### PR DESCRIPTION
**Pull request by hhuseyinpay**
This pull request introduces a `logger` parameter to the `ChargePoint` class's `__init__` function. This allows users to specify a custom logger, enhancing flexibility and control over logging.

### CODE REVIEW

**Comment by hhuseyinpay** [comment]
done

**Comment by jainmohit2001** [comment]
```
ocpp/charge_point.py:209:89: E501 line too long (111 > 88 characters)
```

Need some refactoring here.

**Comment by jainmohit2001** [comment]
There are still some formatting issues. It seems like the New line character is different from what is expected by the code quality check, cause all the visible characters are the same.

**Comment by hhuseyinpay** [comment]
I don't know how to do that. I use Pycharm with default settings

**Comment by jainmohit2001** [comment]
A simple google search may give you this:
https://stackoverflow.com/questions/71040516/change-crlf-to-lf-for-all-files-in-a-pycharm-project

**Comment by jainmohit2001** [comment]
Some more formatting issues.

**Comment by hhuseyinpay** [comment]
I've spent enough time on this. I'm no longer interested in this. You can easily make these changes yourself. If formatting is that important, consider writing a simple pre-commit script.

**Pull request closed without merging**
