### PR TITLE
Revert "drop support for python 3.7"

### PR DESCRIPTION
**Pull request by Jared-Newell-Mobility**
Reverts mobilityhouse/ocpp#585

As this is breaking should be included in release 1.0.0

### CODE REVIEW

**Comment by OrangeTux** [comment]
What's  the reason Python 3.7 support had to be add again? Before dropping the support again in #598 ?

**Comment by Jared-Newell-Mobility** [comment]
I'm a bit confused this was merged yesterday, but this should be part of a major release, are we moving now to 1.0.0?

**Comment by OrangeTux** [comment]
Sure, Python 3.7 should be dropped. I'm as confused as you that Python 3.7 support was added again.

**Comment by Jared-Newell-Mobility** [comment]
Lets then align on this later today

**Pull request merged**
