### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by laysauchoa**
Python 3.10 has been released on 4 Oct, 2021.
We can add support for it.

### CODE REVIEW

**Comment by laysauchoa** [comment]
oh, this image is not yet available.I'll leave it here :)

**Comment by OrangeTux** [comment]
The image is available now. However, the build fails.

**Comment by tropxy** [comment]
There are some incompatibilities with python 3.10 and older versions of pytest [1]. The problem may be there...

[1]: https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest

**Comment by tropxy** [comment]
As we moved to GHA and 3.10 tests were included there, this PR can be closed. Thanks for the initiative @laysauchoa

**Pull request closed without merging**
